# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
s.split(sep=' ')

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [17]:
planet = "Earth"
diameter = 12742
txt = 'The diameter of {planet} is {diameter} kilometers.'

In [21]:
txt.format(planet=planet,diameter=diameter)

'The diameter of Earth is 12742 kilometers.'

## 3. In this nest dictionary grab the word "hello"

In [4]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [5]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [6]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [9]:
np.arange(20,35,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate([a,b])
c

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [12]:
import pandas as pd
df = pd.DataFrame(np.arange(0,6).reshape(3,2))

In [13]:
df

0  1
0  0  1
1  2  3
2  4  5

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [14]:
df = pd.DataFrame()

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [15]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [16]:
pd.DataFrame(lists)

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24